# Generated by Django 2.2.6 on 2019-11-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('NSQID', models.CharField(max_length=64, unique=True)),
                ('ImageUrl', models.URLField()),
                ('SellPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='PENDING', max_length=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('manychat_campaign', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('ItemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sell.Item')),
                ('OrderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sell.Order')),
            ],
        ),
    ]
